apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  # kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
- schedulerName: cacheaware-scheduler
  plugins:
    filter:
      enabled:
      - name: CacheAwarePlugin
    score:
      enabled:
      - name: CacheAwarePlugin
