apiVersion: v1
kind: ConfigMap
metadata:
  name: cacheaware-config
  namespace: {{ .Values.scheduler.namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: scheduler-plugins-scheduler
      plugins:
        filter:
          enabled:
          - name: CacheAwarePlugin
        score:
          enabled:
          - name: CacheAwarePlugin
